export const GET_MOVIE_DETAIL_REQUEST = 'GET_MOVIE_DETAIL_REQUEST'
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS'
export const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_DETAIL_FAIL'

export const GET_ROOM_TICKET_REQUEST = 'GET_ROOM_TICKET_REQUEST'
export const GET_ROOM_TICKET_SUCCESS = 'GET_ROOM_TICKET_SUCCESS'
export const GET_ROOM_TICKET_FAIL = 'GET_ROOM_TICKET_FAIL'

export const GET_THEATERS_REQUEST = 'GET_THEATERS_REQUEST'
export const GET_THEATERS_SUCCESS = 'GET_THEATERS_SUCCESS'
export const GET_THEATERS_FAIL = 'GET_THEATERS_FAIL'

export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST"
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS"
export const BOOK_TICKET_FAIL = "BOOK_TICKET_FAIL"

export const ADD_MOVIE_SHOWTIME_REQUEST = 'ADD_MOVIE_SHOWTIME_REQUEST'
export const ADD_MOVIE_SHOWTIME_SUCCESS = 'ADD_MOVIE_SHOWTIME_SUCCESS'
export const ADD_MOVIE_SHOWTIME_FAIL = 'ADD_MOVIE_SHOWTIME_FAIL'